-- Limpeza LGPD: csv_atendimento_cid_param_bio → atendimentos_cid_ubs.
-- Sem nome/CPF/CNS/NIS do paciente ou profissional.

USE vitacare_mvp;

CREATE TABLE IF NOT EXISTS atendimentos_cid_ubs (
    atendimento_id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    paciente_id              VARCHAR(16)  NULL COMMENT 'P######',
    profissional_id          VARCHAR(16)  NULL COMMENT 'R###### (CNS profissional ou nome)',
    cnes                     VARCHAR(32)  NULL,
    unidade                  VARCHAR(255) NULL,
    ine                      VARCHAR(64)  NULL,
    nome_equipe              VARCHAR(255) NULL,
    ap                       VARCHAR(64)  NULL,
    tipo_atendimento         VARCHAR(128) NULL,
    cbo_profissional         VARCHAR(255) NULL,
    data_consulta            VARCHAR(32)  NULL,
    sexo_paciente            VARCHAR(32)  NULL,
    raca                     VARCHAR(64)  NULL,
    paciente_temporario      VARCHAR(32)  NULL,
    paciente_situacao_rua    VARCHAR(32)  NULL,
    cid_01                   VARCHAR(64)  NULL,
    cid_consulta_diagnostico_01 VARCHAR(255) NULL,
    estado_cid_consulta_01   VARCHAR(64)  NULL,
    cid_02                   VARCHAR(64)  NULL,
    cid_consulta_diagnostico_02 VARCHAR(255) NULL,
    estado_cid_consulta_02   VARCHAR(64)  NULL,
    cid_03                   VARCHAR(64)  NULL,
    cid_consulta_diagnostico_03 VARCHAR(255) NULL,
    estado_cid_consulta_03   VARCHAR(64)  NULL,
    cid_04                   VARCHAR(64)  NULL,
    cid_consulta_diagnostico_04 VARCHAR(255) NULL,
    estado_cid_consulta_04   VARCHAR(64)  NULL,
    cid_05                   VARCHAR(64)  NULL,
    cid_consulta_diagnostico_05 VARCHAR(255) NULL,
    estado_cid_consulta_05   VARCHAR(64)  NULL,
    ciap_consulta_01         VARCHAR(128) NULL,
    ciap_consulta_02         VARCHAR(128) NULL,
    ciap_consulta_03         VARCHAR(128) NULL,
    ciap_consulta_04         VARCHAR(128) NULL,
    ciap_consulta_05         VARCHAR(128) NULL,
    peso                     VARCHAR(32)  NULL,
    altura                   VARCHAR(32)  NULL,
    pa_max                   VARCHAR(32)  NULL,
    pa_min                   VARCHAR(32)  NULL,
    temperatura              VARCHAR(32)  NULL,
    sat_02                   VARCHAR(32)  NULL,
    competencia_extracao     CHAR(7)      NOT NULL,
    carga_id                 BIGINT UNSIGNED NULL,
    linha_origem             INT UNSIGNED NULL,
    PRIMARY KEY (atendimento_id),
    KEY idx_atcid_pac (paciente_id),
    KEY idx_atcid_prof (profissional_id),
    KEY idx_atcid_cnes (cnes),
    KEY idx_atcid_dt (data_consulta),
    KEY idx_atcid_cid1 (cid_01),
    KEY idx_atcid_comp (competencia_extracao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
