-- Limpeza LGPD: acompanhamento diabetes e hipertensão.
-- Sem nome, CPF, CNS (num_sus), prontuário, DNV, data de nascimento.

USE vitacare_mvp;

CREATE TABLE IF NOT EXISTS acompanhamento_diab_ubs (
    acomp_id                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    paciente_id                  VARCHAR(16)  NULL COMMENT 'P######',
    cnes                         VARCHAR(32)  NULL,
    unidade                      VARCHAR(255) NULL,
    area_familia                 VARCHAR(32)  NULL,
    microarea_familia            VARCHAR(32)  NULL,
    ta_min_2                     VARCHAR(16)  NULL,
    ta_max_2                     VARCHAR(16)  NULL,
    ta_data_2                    VARCHAR(16)  NULL,
    hba1c                        VARCHAR(16)  NULL,
    hba1c_data                   VARCHAR(16)  NULL,
    exame_pe_esq                 VARCHAR(32)  NULL,
    exame_pe_dir                 VARCHAR(32)  NULL,
    exame_pes_data               VARCHAR(32)  NULL,
    ldl                          VARCHAR(16)  NULL,
    ldl_data                     VARCHAR(16)  NULL,
    hdl                          VARCHAR(16)  NULL,
    hdl_data                     VARCHAR(16)  NULL,
    colesterol_total             VARCHAR(32)  NULL,
    colesterol_total_data        VARCHAR(32)  NULL,
    triglicerideos               VARCHAR(32)  NULL,
    triglicerideos_data          VARCHAR(32)  NULL,
    microalbuminuria             VARCHAR(32)  NULL,
    microalbuminuria_data        VARCHAR(32)  NULL,
    encaminhamento_oftalm_data   VARCHAR(32)  NULL,
    esq_acuidade_visual          VARCHAR(32)  NULL,
    esq_acuidade_visual_data     VARCHAR(32)  NULL,
    dir_acuidade_visual          VARCHAR(32)  NULL,
    dir_acuidade_visual_data     VARCHAR(32)  NULL,
    dir_retinavis                VARCHAR(32)  NULL,
    dir_retinavis_data           VARCHAR(32)  NULL,
    esq_retinavis                VARCHAR(32)  NULL,
    esq_retinavis_data           VARCHAR(32)  NULL,
    dir_retinopatia              VARCHAR(32)  NULL,
    dir_retinopatia_data         VARCHAR(32)  NULL,
    esq_retinopatia              VARCHAR(32)  NULL,
    esq_retinopatia_data         VARCHAR(32)  NULL,
    ult_cons_med                 VARCHAR(32)  NULL,
    qtd_cons_diab_12meses        VARCHAR(32)  NULL
        COMMENT 'janela móvel — não somar meses como eventos novos',
    competencia_extracao         CHAR(7)      NOT NULL,
    carga_id                     BIGINT UNSIGNED NULL,
    linha_origem                 INT UNSIGNED NULL,
    PRIMARY KEY (acomp_id),
    KEY idx_diab_pac (paciente_id),
    KEY idx_diab_cnes (cnes),
    KEY idx_diab_comp (competencia_extracao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS acompanhamento_hiper_ubs (
    acomp_id                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    paciente_id                  VARCHAR(16)  NULL COMMENT 'P######',
    cnes                         VARCHAR(32)  NULL,
    unidade                      VARCHAR(255) NULL,
    area_familia                 VARCHAR(32)  NULL,
    microarea_familia            VARCHAR(32)  NULL,
    ta_min_2                     VARCHAR(16)  NULL,
    ta_max_2                     VARCHAR(16)  NULL,
    ta_data_2                    VARCHAR(16)  NULL,
    data_ultima_consulta         VARCHAR(32)  NULL,
    microalbuminuria             VARCHAR(32)  NULL,
    microalbuminuria_data         VARCHAR(32)  NULL,
    colesterol_total             VARCHAR(32)  NULL,
    colesterol_total_data        VARCHAR(32)  NULL,
    hdl                          VARCHAR(16)  NULL,
    hdl_data                     VARCHAR(16)  NULL,
    triglicerideos               VARCHAR(32)  NULL,
    triglicerideos_data          VARCHAR(32)  NULL,
    proteinuria                  VARCHAR(32)  NULL,
    proteinuria_data             VARCHAR(32)  NULL,
    competencia_extracao         CHAR(7)      NOT NULL,
    carga_id                     BIGINT UNSIGNED NULL,
    linha_origem                 INT UNSIGNED NULL,
    PRIMARY KEY (acomp_id),
    KEY idx_hiper_pac (paciente_id),
    KEY idx_hiper_cnes (cnes),
    KEY idx_hiper_comp (competencia_extracao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
